name = "CoqToLeanAsm"
version = "0.1.0"
defaultTargets = ["coqtoleanasm"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = true
relaxedAutoImplicit = false
linter.missingDocs = true
doc.verso = true


[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.25.0"

[[lean_lib]]
name = "CoqToLeanAsm"
glob = ["CoqToLeanAsm.*"]

[[lean_lib]]
name = "X86Docs"
glob = ["X86Docs.*"]

[[lean_exe]]
name = "coqtoleanasm"
root = "Main"

[[lean_exe]]
name = "x86docs"
root = "X86DocsMain"
